### ISSUE TITLE
DB Prefix issue

### ISSUE THREAD

**Issue by sabansen** [jtl-software/connector-prestashop#11]
Dear JTL Team, I have using Prestashop Connector for a while also tracking close to improve some features too. I would like to report a small prefix issue. 

https://github.com/jtl-software/connector-prestashop/blob/b224a3d43bdd4fce2c71f2634d79d1e8498cf9be/src/Controller/CustomerOrder.php#L12

If someone uses a different prefix like me, sync won't work through.

Solution:  '._DB_PREFIX_.'orders

PS: When I find issues/solutions, I would like also to contribute.

Best regards

**Comment by drieschel** [comment]
Hello @sabansen!

Thank you for creating this issue. 👍  We would love to see your contributions by opening a pull request. Don't hesitate to ask if you have further questions.

Best regards from very western Germany 😄

**Comment by drieschel** [comment]
We will take care of it. :-)
