### ISSUE TITLE
Feature request: watermark hooks

### ISSUE THREAD

**Issue by NulAsh** [jtl-software/connector-prestashop#12]
Hello. Could you please add watermark hooks to https://github.com/jtl-software/connector-prestashop/blob/master/src/Controller/Image.php ?
So watermark modules will be able to process uploaded images.
Something like `Hook::exec('actionWatermark', ['id_image' => $id_image, 'id_product' => $id_product]);`
You can see such lines in Prestashop source code in following files:
```
/classes/QqUploadedFileForm.php
/classes/QqUploadedFileXhr.php
/classes/webservice/WebserviceSpecificManagementImages.php
/controllers/admin/AdminImagesController.php
/controllers/admin/AdminImportController.php
/controllers/admin/AdminProductsController.php
/src/Adapter/Import/ImageCopier.php
/src/Adapter/Product/Image/Uploader/ProductImageUploader.php
```
Just search by text "actionWatermark".
I suppose, it should be inserted in two places:

1. after [this line](https://github.com/jtl-software/connector-prestashop/blob/b6dbd31ea72f065bf6deb732e59ec6866498f005/src/Controller/Image.php#L196)

2. and [here](https://github.com/jtl-software/connector-prestashop/blob/b6dbd31ea72f065bf6deb732e59ec6866498f005/src/Controller/Image.php#L211)

**Comment by paprykasz** [comment]
Hey @NulAsh 

Thank you for your feedback. We need to check this issue, but I think it should be possible to add this action for watermark generation as you suggested.

**Comment by paprykasz** [comment]
Added in 1.13.0
