### ISSUE TITLE
Extra Features

### ISSUE THREAD

**Issue by RWService** [jtl-software/connector-prestashop#2]
Hello Dear Chakratos,

I would like to make the Prestashop integration more deeply: push tracking number Presta, change invoice path and payment status.
 
And i want to know if it possible to add those features in your code or there are restrictions in JTL Wawi client app and i need to go another way and make it with a Webrequest API(IMHO not very nice solution).

Asking you because the code of JTL is closed.

Best Regards,
Aleksandr

**Comment by Chakratos** [comment]
Hello RWService,

Sorry for the late response, i wasn't in the office last week ;)
So you want to push these informations from the JTL-Wawi to Prestashop?
Tracking number should be implemented already, if you pulled an order into the JTL-Wawi and then add a tracking_number there, the Wawi should make an DeliveryNote push with the tracking number (Numbers if there are multiple)

You can see the corresponding code in: src\Controller\DeliveryNote.php

What exactly do you mean by "Invoice path"?

There is an "Payment status" and an "Order status" that should be pushed by the Wawi to the Connector after you've processed the Order. (example: STATUS_CANCELLED, PAYMENT_STATUS_COMPLETED, STATUS_SHIPPED)

You can see the corresponding code in src\Controller\StatusChange.php
