### ISSUE TITLE
Can't sync Group's Prices

### ISSUE THREAD

**Issue by RWService** [jtl-software/connector-prestashop#3]
Good day,

I am experiencing troubles with syncing group's prices from Wawi to Prestashop.

How to reproduce:
Upload the products to Wawi > push data to prestashop > update the price in wawi using "Price Calculator" or you adjust few products prices manually > push data to prestashop. **Group's prices will not be updated.**

My workaround:

Group's prices will be updated if you DROP/Erase the table specific_price in Prestashop first, in Wawi change the price for all the products for 0,01 EUR (or any changes), then push everything back to Prestashop. 

The thing is that it's happened only if **more then one product** price is changes and need to be pushed.

I was also trying to fix it myself but my skills do not allow me to find a reason. I only find out that only "main" Price is updating but group's price stay untouched. BUT if you adjust only one product's price everything will be fine.

I can also make a video from the screen if it will be required.

**Comment by drieschel** [comment]
@RWService Does the problem still exist?
